version: '3'

services:
  
  nginx_dev:
    build: nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend

  frontend:
    build: client
    expose:
      - 8000
    volumes:
      - ./client:/src
  
  backend: 
    build: server
    expose:
      - 8000
    volumes:
      - ./server:/server